# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 65ea57c0d9833c4273f187b5231e46ec444119c1313c0828623e90945b483317bab761a119c8cd0c9494bce2e6e5c4a29cf81805c1ec9ac3e18a46aeada713f3

test:
  secret_key_base: e044c8982ee090aa61102ac0c5f2b84e22c0cc291b777cb2e3782c1529cd16767421dc61a6acf2732bfcd708ea6741ebfc2f18fd7cbeec092d99b743bd55e71e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
